server:
  port: 8081

spring:
  config:
    import: classpath:env.yml
  application:
    name: springboot-jpa
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      jakarta:
        persistence:
          validation:
            mode: none
  data:
    rest:
      base-path: /data-api
logging:
  level:
    root: INFO
    com:
      suleware:
        eazyschool:
          example_18:
            aspects: ERROR
  file:
    name: file.log
  logback:
    rollingpolicy:
      file-name-pattern: demofile.%d{yyyy-MM-dd}.%i.gz.log
      max-file-size:
        10MB
      total-size-cap:
        1GB
      clean-history-on-start: true